version: '3.8'

networks:
  network:
    name: network
    driver: bridge

services:
  keycloak:
    container_name: keycloak_service
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - 8080:8080
    volumes:
      - ./keycloak_data:/opt/jboss/keycloak/standalone/data
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_data:/var/lib/postgresql/data
  
  # frontend:
  #   container_name: frontend_service
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - keycloak
  #     - backend
  #   networks:
  #     - network
  
  # neo4j_db:
  #   container_name: neo4j_db
  #   image: neo4j:latest
  #   ports:
  #    - 7474:7474
  #    - 7687:7687
  #   restart: unless-stopped
  #   environment:
  #     - NEO4J_AUTH=neo4j/maslo123
  #   volumes:
  #     - ../neo4j/db/data:/data
  #     - ../neo4j/db/conf:/conf
  #     - ../neo4j/db/logs:/logs
  #     - ../neo4j/db/plugins:/plugins
  #   networks:
  #     - network

  # backend: 
  #   container_name: backend_service
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 1337:1337
  #   depends_on:
  #     - keycloak
  #     - neo4j_db
  #   networks:
  #     - network
  



      
      
    
